server:
  port: 8084

spring:
  # config:
  #   import: configserver:http://localhost:8082


  datasource:
    url: jdbc:mysql://localhost:3306/FlightSearchService?createDatabaseIfNotExist=true
    username: root
    password: Suraj@1629
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    